import {
  ACCENT_COLOR_STORAGE_KEY,
  CHECK_IN_FORM_COLLAPSED_STORAGE_KEY,
  CLEAR_TAG_FILTERS_ON_SHEET_CHANGE_STORAGE_KEY,
  COLOR_PALETTE_STORAGE_KEY,
  CONFIRM_BEFORE_CHECKOUT_STORAGE_KEY,
  CONFIRM_DESTRUCTIVE_ACTIONS_STORAGE_KEY,
  DEFAULT_REPORTING_RANGE_STORAGE_KEY,
  DEFAULT_REPORTING_SORT_STORAGE_KEY,
  DURATION_FORMAT_STORAGE_KEY,
  ENTRY_LIST_SORT_STORAGE_KEY,
  GREEDY_CLOUD_SYNC_STORAGE_KEY,
  TAG_FILTER_MODE_STORAGE_KEY,
  THEME_MODE_STORAGE_KEY,
  TIME_FORMAT_STORAGE_KEY,
  TIMER_IN_TITLE_STORAGE_KEY,
  TIMER_SHOW_SECONDS_STORAGE_KEY,
  WEEK_STARTS_ON_STORAGE_KEY,
} from '@/lib/types/ui_preferences'
import {
  ACTIVE_SHEET_STORAGE_KEY,
  COMPACT_LISTS_STORAGE_KEY,
  DEFAULT_SHEET_FIXED_NAME_STORAGE_KEY,
  DEFAULT_SHEET_SESSION_MODE_STORAGE_KEY,
  SHEET_TAG_FILTERS_STORAGE_KEY,
} from '@/lib/types/ui_settings'
import { THEME_STORAGE_KEY } from '@/lib/types/theme'

/**
 * Returns every localStorage key synced to Supabase when signed in.
 */
export function list_ui_preference_storage_keys(): string[] {
  return [
    ACCENT_COLOR_STORAGE_KEY,
    ACTIVE_SHEET_STORAGE_KEY,
    CHECK_IN_FORM_COLLAPSED_STORAGE_KEY,
    CLEAR_TAG_FILTERS_ON_SHEET_CHANGE_STORAGE_KEY,
    COLOR_PALETTE_STORAGE_KEY,
    COMPACT_LISTS_STORAGE_KEY,
    CONFIRM_BEFORE_CHECKOUT_STORAGE_KEY,
    CONFIRM_DESTRUCTIVE_ACTIONS_STORAGE_KEY,
    DEFAULT_REPORTING_RANGE_STORAGE_KEY,
    DEFAULT_REPORTING_SORT_STORAGE_KEY,
    DEFAULT_SHEET_FIXED_NAME_STORAGE_KEY,
    DEFAULT_SHEET_SESSION_MODE_STORAGE_KEY,
    DURATION_FORMAT_STORAGE_KEY,
    ENTRY_LIST_SORT_STORAGE_KEY,
    GREEDY_CLOUD_SYNC_STORAGE_KEY,
    SHEET_TAG_FILTERS_STORAGE_KEY,
    TAG_FILTER_MODE_STORAGE_KEY,
    THEME_MODE_STORAGE_KEY,
    THEME_STORAGE_KEY,
    TIME_FORMAT_STORAGE_KEY,
    TIMER_IN_TITLE_STORAGE_KEY,
    TIMER_SHOW_SECONDS_STORAGE_KEY,
    WEEK_STARTS_ON_STORAGE_KEY,
  ]
}
